import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header/Header";
import { Abel } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });
const abel = Abel({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${abel.className}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
